# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskTokBoxApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaskTokBoxApp
pod 'OpenTok'

  target 'TaskTokBoxAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TaskTokBoxApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaskTokBoxApp-tvOS

  target 'TaskTokBoxApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
